[tool.mypy]
python_version = "3.13"
warn_return_any = false
warn_unused_configs = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false
warn_redundant_casts = false
warn_unused_ignores = false
warn_no_return = false
warn_unreachable = false
strict_equality = false
ignore_errors = false

# Ignore missing imports for libraries without type stubs
[[tool.mypy.overrides]]
module = [
    "requests.*",
    "tqdm.*",
    "pandas.*",
    "numpy.*",
    "openpyxl.*",
    "aiohttp.*"
]
ignore_missing_imports = true
